<table>
    <tr>
        <th>
            <?= __("Id")?>
        </th>
        <th>
            <?= __("Name")?>
        </th>
        <th>
            <?= __("Phone")?>
        </th>
        <th>
            <?= __("Email")?>
        </th>
        <th>
            <?= __("Action")?>
        </th>
    </tr>
    <?php
    $rows = $block->getDetails();
      foreach ($rows as $row) {
        ?>
    <tr>
        <td>
            <?= $row->getId()?>
        </td>
        <td>
            <?= $row->getName()?>
        </td>
        <td>
            <?= $row->getPhone()?>
        </td>
        <td>
            <?= $row->getEmail()?>
        </td>
        <td>
            <button><a href="<?= $block->getUrl('students/manage/update').'id/'.$row->getId();?>">
            <?= __('Update') ?>
            </a></button>
            <button><a href="<?= $block->getUrl('students/manage/delete', ['id'=>$row->getId()])?>"
                onclick="return confirm('Are you sure you want to delete this Student?');">
                <?= __('Delete') ?>
            </a></button>
        </td>

    </tr>
    <?php } ?>
</table>