<?php

/**
 * @var \DCKAP\Common\Block\Footer $block
 */
?>
<style>
    #automotive_footer_industrydisplay {
        display: hidden;
    }
</style>
<ul class="footer links" id="automotive_footer_industry">
    <li class="nav item">
        <a href="automotive"><?php echo _('Automotive'); ?></a>
    </li>
    <li class="nav item">
        <a href="automotive/agricultural"><?php echo _('Agricultural'); ?></a>
    </li>
    <li class="nav item">
        <a href="automotive/heavy-duty"><?php echo _('Heavy-Duty'); ?></a>
    </li>
    <li class="nav item">
        <a href="automotive/marine"><?php echo _('Marine'); ?></a>
    </li>
    <li class="nav item">
        <a href="automotive/material-handling"><?php echo _('Material Handling'); ?></a>
    </li>
    <li class="nav item">
        <a href="automotive/marine"><?php echo _('Marine'); ?></a>
    </li>
    <li class="nav item">
        <a href="automotive/material-handling"><?php echo _('Material Handling'); ?></a>
    </li>
    <li class="nav item">
        <a href="automotive/mining"><?php echo _('Mining'); ?></a>
    </li>
    </li>
    <li class="nav item">
        <a href="automotive/recreational-vehicles"><?php echo _('Recreational Vehicles'); ?></a>
    </li>
    <li class="nav item">
        <a href="automotive/transportation"><?php echo _('Transportation'); ?></a>
    </li>

    <li class="nav item">
        <a href="automotive/truck-trailer"><?php echo _('Truck & Trailer'); ?></a>
    </li>
</ul>